temp7

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -1,40 +1,40 @@
-name: "Terraform-apply-infrastructure"
+# name: "Terraform-apply-infrastructure"
 
-on:
-  push:
-    branches:
-      - GithubActions-Assignment 
+# on:
+#   push:
+#     branches:
+#       - main 
 
-jobs:
-  terraform:
-    name: "Terraform"
-    runs-on: self-hosted
-    defaults:
-      run:
-        working-directory: GithubActions-Assignment
+# jobs:
+#   terraform:
+#     name: "Terraform"
+#     runs-on: self-hosted
+#     defaults:
+#       run:
+#         working-directory: GithubActions-Assignment
 
-    steps:  
-      - name: Checkout
-        uses: actions/checkout@v2
+#     steps:  
+#       - name: Checkout
+#         uses: actions/checkout@v2
         
-      - name: Terraform Init
-        id: init
-        run: terraform init
+#       - name: Terraform Init
+#         id: init
+#         run: terraform init
 
-      - name: Terraform Plan
-        id: plan
-        if: github.event_name == 'push'
-        run: terraform plan -no-color
-        continue-on-error: true
+#       - name: Terraform Plan
+#         id: plan
+#         if: github.event_name == 'push'
+#         run: terraform plan -no-color
+#         continue-on-error: true
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+#       - name: Terraform Plan Status
+#         if: steps.plan.outcome == 'failure'
+#         run: exit 1
 
-      - name: Terraform Apply
-        if: github.event_name == 'push'
-        run: terraform apply -auto-approve
+#       - name: Terraform Apply
+#         if: github.event_name == 'push'
+#         run: terraform apply -auto-approve
 
-      - name: Terraform Destroy
-        id: destroy
-        run: terraform destroy -auto-approve
+#       - name: Terraform Destroy
+#         id: destroy
+#         run: terraform destroy -auto-approve
